#Made By Beta-Development
loginSpawn:
  world: world
  x: 0
  y: 70
  z: 0
  yaw: 0
  pitch: 0
lobbySpawn:
  world: world
  x: 0
  y: 70
  z: 0
  yaw: 0
  pitch: 0
timeOutEnabled: true
timeOutSeconds: 15
disableOpWhenQuit: true

#Plugin Version 1.0 // dont worry, end of the configuration files
